[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  STABILITY_API_KEY = "sk-Ivk1XG8TpG9zNuaEosqmfGWYkVYlAXe7DhG9RWr9HCKCRk6h"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200